name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Step 2
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Test"

  approve:
    name: Approve
    runs-on: ubuntu-latest
    environment: homolog
    needs: test
    steps:
      - name: Approve
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Approve"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: homolog2
    needs: approve
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Deploy"
