name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Step 2
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Test"

  approve1:
    name: Approve 1
    runs-on: ubuntu-latest
    environment: homolog
    needs: test
    steps:
      - name: Approve
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Approve 1"

  approve2:
    name: Approve 2
    runs-on: ubuntu-latest
    environment: homolog
    needs: test
    steps:
      - name: Approve
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Approve 2"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: homolog3
    needs: [approve1, approve2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Deploy"
